name: Updater (WIP)

on:
  schedule:
    - cron: 30 23 * * *
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: wowchemy/gh-action-updater@v1
        with:
          feed-url: https://wowchemy.com/blog/index.xml
          readme-section: news
